services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: lightning_nodes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lightning_nodes"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql]

  # ==> If you want the entire application to run via Docker, uncomment the lines below.
  
  # app:
  #   build: .
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     APP_HOST: 0.0.0.0
  #     APP_PORT: 3000
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/lightning_nodes
  #     DATABASE_MAX_CONNECTIONS: 10
  #     DATABASE_MIN_CONNECTIONS: 1
  #     GATEWAY_MEMPOOL_URL: https://mempool.space/api/v1/lightning/nodes/rankings/connectivity
  #     RUST_LOG: lightning_nodes_service=info,tower_http=info
  #   ports: ["3000:3000"]

volumes:
  postgres_data:
